# Generated by Django 5.0.2 on 2024-05-01 12:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUsers',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=100)),
                ('account_level', models.CharField(choices=[('1', 'Premium1'), ('2', 'Premium2'), ('3', 'Premium3')], default='1', max_length=20)),
                ('access_level', models.CharField(choices=[('1', 'Read'), ('2', 'ReadWrite'), ('3', 'Admin')], default='1', max_length=20)),
                ('pf_photo', models.CharField(default='https://www.pngall.com/wp-content/uploads/5/Profile-PNG-Free-Download.png', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('ref_id', models.TextField()),
                ('reports', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.eusers')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('ref_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_photo', models.TextField(default='https://flowbite.com/docs/images/blog/image-1.jpg')),
                ('level', models.CharField(choices=[('1', 'Premium1'), ('2', 'Premium2'), ('3', 'Premium3')], default='1', max_length=20)),
                ('topic', models.CharField(choices=[('1', 'Topic 1'), ('2', 'Topic 2'), ('3', 'Topic 3'), ('4', 'Misc')], default='1', max_length=20)),
                ('title', models.TextField(unique=True)),
                ('content', models.TextField()),
                ('html_content', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'InReview'), ('3', 'Published')], default='1', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('md', models.TextField()),
                ('comments', models.ManyToManyField(blank=True, related_name='blogs', to='api.comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_blogs', to='api.eusers')),
            ],
        ),
    ]
