# Generated by Django 5.0.2 on 2024-04-13 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('pfPhoto', models.TextField(blank=True, default='', null=True)),
                ('level', models.TextField(default=('1', 'Premium1'))),
                ('name', models.TextField()),
                ('refId', models.TextField()),
                ('title', models.TextField(unique=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'InReview'), ('3', 'Published')], default='1', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 3, 41, 885654))),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=list, null=True)),
                ('md', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default='9efb63c7-be6b-58e1-9b48-739bd01b498d')),
                ('uid', models.TextField()),
                ('name', models.TextField()),
                ('pfPhoto', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 15, 3, 41, 885654))),
                ('comment', models.TextField()),
                ('refId', models.TextField()),
                ('reports', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=100)),
                ('account_level', models.CharField(choices=[('1', 'Premium1'), ('2', 'Premium2'), ('3', 'Premium3')], default='1', max_length=20)),
                ('access_level', models.CharField(choices=[('1', 'Read'), ('2', 'ReadWrite'), ('3', 'Admin')], default='1', max_length=20)),
                ('pfPhoto', models.CharField(default='https://www.pngall.com/wp-content/uploads/5/Profile-PNG-Free-Download.png', max_length=256)),
                ('likedPosts', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
