# Generated by Django 5.0.2 on 2024-04-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eusers',
            name='access_levels',
            field=models.CharField(default='r', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eusers',
            name='level',
            field=models.CharField(default='premium1', max_length=6),
            preserve_default=False,
        ),
    ]
