# Generated by Django 5.0.2 on 2024-04-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eusers_access_levels_eusers_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eusers',
            name='level',
        ),
        migrations.AddField(
            model_name='eusers',
            name='semester',
            field=models.CharField(choices=[('1', 'Premium1'), ('2', 'Premium2'), ('3', 'Premium3')], default='1', max_length=20),
        ),
    ]
