# Generated by Django 5.0.2 on 2024-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_html_content_blog_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='eusers',
            name='likedPosts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
