# Generated by Django 5.0.2 on 2024-04-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_eusers_level_eusers_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eusers',
            old_name='semester',
            new_name='account_levels',
        ),
        migrations.AlterField(
            model_name='eusers',
            name='access_levels',
            field=models.CharField(choices=[('1', 'Read'), ('2', 'ReadWrite'), ('3', 'Admin')], default='1', max_length=20),
        ),
    ]
