# Generated by Django 5.0.2 on 2024-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comment_ref_id_eusers_likedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('Topic 1', 'Topic 1'), ('Topic 2', 'Topic 2'), ('Topic 3', 'Topic 3'), ('Misc', 'Misc')], default='Topic 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='account_level',
            field=models.CharField(choices=[('Premium1', 'Premium1'), ('Premium2', 'Premium2'), ('Premium3', 'Premium3')], default='Premium1', max_length=20),
        ),
    ]
