# Generated by Django 5.0.2 on 2024-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_topic_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='level',
            field=models.CharField(choices=[('1', 'Premium1'), ('2', 'Premium2'), ('3', 'Premium3')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('Topic 1', 'Topic 1'), ('Topic 2', 'Topic 2'), ('3', 'Topic3'), ('4', 'Misc')], default='1', max_length=20),
        ),
    ]
