# Generated by Django 5.0.2 on 2024-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_topic_alter_eusers_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eusers',
            name='account_level',
            field=models.CharField(choices=[('Premium 1', 'Premium2'), ('Premium 2', 'Premium2'), ('Premium 3', 'Premium3')], default='Premium 1', max_length=20),
        ),
    ]
