# Generated by Django 5.0.2 on 2024-04-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_semester_eusers_account_levels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eusers',
            old_name='access_levels',
            new_name='access_level',
        ),
        migrations.RenameField(
            model_name='eusers',
            old_name='account_levels',
            new_name='account_level',
        ),
    ]
