# Generated by Django 5.0.2 on 2024-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blog_level_alter_blog_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('Topic 1', 'Topic 1'), ('Topic 2', 'Topic 2'), ('Topic 3', 'Topic3'), ('Msc', 'Misc')], default='1', max_length=20),
        ),
    ]
