# Generated by Django 5.0.2 on 2024-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_access_levels_eusers_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eusers',
            name='pfPhoto',
            field=models.CharField(default='', max_length=256),
        ),
    ]
