# Generated by Django 5.0.2 on 2024-04-10 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_eusers_pfphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('name', models.TextField()),
                ('refId', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'InReview'), ('3', 'Published')], default='1', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 10, 17, 46, 33, 172129))),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.JSONField(default=[{}])),
            ],
        ),
        migrations.AddField(
            model_name='eusers',
            name='phone',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eusers',
            name='uid',
            field=models.TextField(default='8d40fdd7-c497-537d-89ac-7b8062fe7898', unique=True),
            preserve_default=False,
        ),
    ]
