# Generated by Django 5.0.2 on 2024-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blog_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coverPhoto',
            field=models.TextField(default='https://flowbite.com/docs/images/blog/image-1.jpg'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.CharField(choices=[('1', 'Topic 1'), ('2', 'Topic 2'), ('3', 'Topic 3'), ('4', 'Misc')], default='1', max_length=20),
        ),
    ]
