# Generated by Django 5.0.2 on 2024-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_eusers_account_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft 1'), ('InReview', 'InReview 1'), ('Published', 'Published 1')], default='1', max_length=20),
        ),
    ]
