# Generated by Django 5.0.2 on 2024-04-10 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blog_eusers_phone_eusers_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 21, 22, 27, 148255)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
