# Generated by Django 5.0.2 on 2024-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.TextField(choices=[('Draft', 'Draft'), ('InReview', 'InReview'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='topic',
            field=models.TextField(choices=[('Topic 1', 'Topic 1'), ('Topic 2', 'Topic 2'), ('Topic 3', 'Topic 3'), ('Misc', 'Misc')], default='Topic 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='access_level',
            field=models.TextField(choices=[('Read', 'Read'), ('ReadWrite', 'ReadWrite'), ('Admin', 'Admin')], default='Read', max_length=20),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='account_level',
            field=models.TextField(choices=[('Premium 1', 'Premium1'), ('Premium 2', 'Premium2'), ('Premium 3', 'Premium3')], default='Premium 1', max_length=20),
        ),
    ]
