# Generated by Django 5.0.2 on 2024-04-11 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blog_date_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='eusers',
            name='likedPosts',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 13, 11, 25, 966686)),
        ),
    ]
