# Generated by Django 5.0.2 on 2024-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_blog_status_alter_blog_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='delta',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='md',
        ),
        migrations.AddField(
            model_name='blog',
            name='domain',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.TextField(choices=[('All', 'All'), ('Mens', 'Mens'), ('Female', 'Female'), ('LGBTQ', 'LGBTQ')], default='All', max_length=20),
        ),
    ]
