# Generated by Django 5.0.2 on 2024-04-11 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_eusers_likedposts_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 15, 35, 2, 280357)),
        ),
    ]
