# Generated by Django 5.0.2 on 2024-05-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_content_blog_delta_remove_blog_md_blog_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviewer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_blogs', to='api.eusers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
