# Generated by Django 5.0.2 on 2024-04-11 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_blog_comments_alter_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.UUIDField(default='443c26a7-cf97-56b1-9590-d245ce811a1c')),
                ('uid', models.TextField()),
                ('name', models.TextField()),
                ('pfPhoto', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 28, 1, 232023))),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 28, 1, 231024)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='pfPhoto',
            field=models.CharField(default='https://www.pngall.com/wp-content/uploads/5/Profile-PNG-Free-Download.png', max_length=256),
        ),
    ]
