# Generated by Django 5.0.2 on 2024-04-11 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment_refid_alter_blog_date_alter_comment_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 46, 42, 493105)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='d0dcd2ac-7c0e-5008-a45e-20a719c4c630'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 46, 42, 493105)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='likedPosts',
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
