# Generated by Django 5.0.2 on 2024-04-11 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 48, 19, 136249)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='c9371637-9d17-576e-a15e-2509ca7b0523'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 48, 19, 136249)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
