# Generated by Django 5.0.2 on 2024-04-11 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 49, 38, 543322)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='17e528d3-500e-53c9-a915-96d0ea85539c'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 18, 49, 38, 543322)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='likedPosts',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
