# Generated by Django 5.0.2 on 2024-04-11 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='md',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 19, 38, 38, 319036)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='ce684a79-282b-559d-8b72-8039eb311bae'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 19, 38, 38, 319036)),
        ),
    ]
