# Generated by Django 5.0.2 on 2024-04-11 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_blog_comments_alter_blog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 1, 11, 4, 161915)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='357cc652-c0d6-5de5-82e8-540e659ba220'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 1, 11, 4, 161915)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='likedPosts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
