# Generated by Django 5.0.2 on 2024-04-11 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_comment_reports_alter_blog_date_alter_comment_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 1, 28, 47, 64148)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='b04c72ac-9948-5c9d-bd33-4679dce7ca48'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 1, 28, 47, 64148)),
        ),
    ]
