# Generated by Django 5.0.2 on 2024-04-12 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_blog_date_alter_comment_cid_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 21, 49, 865534)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='a616684b-5af2-5347-83d4-745b2074aef9'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 21, 49, 865534)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.TextField(null=True, unique=True),
        ),
    ]
