# Generated by Django 5.0.2 on 2024-04-12 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 23, 7, 374609)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='f44ede15-93d1-54f5-9539-5920b35f838b'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 23, 7, 374609)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.TextField(blank=True, default='', unique=True),
            preserve_default=False,
        ),
    ]
