# Generated by Django 5.0.2 on 2024-04-12 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 24, 49, 999041)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='1ace9d80-33fd-5808-bd86-0005351d9ea0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 24, 49, 999041)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
