# Generated by Django 5.0.2 on 2024-04-12 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 28, 43, 197613)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='a2e1f831-e688-58c3-ae9a-97b44a9cfa00'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 28, 43, 197613)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
