# Generated by Django 5.0.2 on 2024-04-12 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_blog_date_alter_comment_cid_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 39, 36, 911991)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='26eba71d-caf4-55c7-acf3-3ae62bf0e03d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 39, 36, 911991)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
