# Generated by Django 5.0.2 on 2024-04-12 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_blog_date_alter_comment_cid_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 43, 32, 454861)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='1b976527-8ecb-5717-b25d-8a7392b1f15e'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 43, 32, 454861)),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
