# Generated by Django 5.0.2 on 2024-04-13 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_blog_date_alter_comment_cid_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pfPhoto',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 40, 18, 258921)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='27aa730b-31be-5b65-84cc-2be141e28f67'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 40, 18, 258921)),
        ),
    ]
