# Generated by Django 5.0.2 on 2024-04-13 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_blog_pfphoto_alter_blog_date_alter_comment_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='level',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 41, 6, 928276)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='327feaef-c925-5363-bf16-ad2c54cd92b0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 41, 6, 928276)),
        ),
    ]
