# Generated by Django 5.0.2 on 2024-04-13 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_blog_date_alter_comment_cid_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 55, 40, 132519)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='level',
            field=models.TextField(default=('1', 'Premium1')),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pfPhoto',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.UUIDField(default='74ac4480-c5fa-5519-95ee-a415873e23e5'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 12, 55, 40, 132519)),
        ),
    ]
